#!/bin/bash -e

docker run --rm \
  -v $(pwd):/src \
  -v /var/run/docker.sock:/var/run/docker.sock \
  centurylink/golang-builder \
  christianbladescb/tiny-etcd

#docker push christianbladescb/tiny-etcd
